### ISSUE TITLE
Subgoals/actions inconsistency

### ISSUE THREAD

**Issue by diananova** [diananova/GenderMagRecordersAssistant#11]
Feature description:
Fix the bug that creates inconsistencies with subgoals and actions. 

Reason for the feature or improvement:
there seems to be bugs with subgoals/actions rewriting over each other and past subgoals/actions disappearing

How does your idea fit with the aim/scope of the project?
Fixes a pretty important bug that has an impact on how the data is collected and saved in the CSV file.

What are the merits of the feature?
Functionality.

**Comment by emlabor** [comment]
I think I've solved the issue of overwriting subgoals (please test my commit for yourself), but while testing noticed a related bug with actions. If you create an action but do not complete all the steps for it, the action is added under every subgoal. Not sure if this is a storage problem or just an issue with output.

**Comment by emlabor** [comment]
I'm going to close this issue and open a few more specific ones.
